apiVersion: apps/v1
kind: Deployment
metadata:
  name: kii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kii
  template:
    metadata:
      labels:
        app: kii
    spec:
      containers:
      - name: site
        image: registry.gitlab.com/ii/nz:2021.09.16.1435
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kii
spec:
  selector:
    app: kii
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
